### ISSUE TITLE
Design: Find the right balance of “it’s so cute!” and “it’s obviously a camera”

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/fomo-camera#1]
I think you need something that:

* Looks like a camera (so it’s really obvious which direction to point it in)
* Looks like a creature with a face (so people look after it)
* Feels comfortable to hold (so people hold it)

Extra points if it lights up, or otherwise attracts attention to itself, so people notice it on the night.

None of these are quite right, but hopefully you can take bits from each (“this one looks a bit like a camera” … “this one is really cute” … “this one is furry”) as inspiration for FOMOcam.

![1739b553fbe03e782931e3db4462e27d_cute-monster-clipart-vectors-cute-monster-clipart_340-270](https://cloud.githubusercontent.com/assets/739624/23630348/b8f14806-02b2-11e7-980f-bf2c6640acca.jpeg)

![2014-01-30-origamiroombio](https://cloud.githubusercontent.com/assets/739624/23630354/bc45e2e6-02b2-11e7-8f1b-4d022d0cbd2f.jpg)

![693273703_556](https://cloud.githubusercontent.com/assets/739624/23630357/bf07c062-02b2-11e7-92a5-d391006c9f75.jpg)

![cameracrazy1](https://cloud.githubusercontent.com/assets/739624/23630361/c12c62e4-02b2-11e7-8208-47b138609440.jpg)

![img_7263](https://cloud.githubusercontent.com/assets/739624/23630365/c3be3a6e-02b2-11e7-843d-7d364bacb573.jpg)

![disderi-camera](https://cloud.githubusercontent.com/assets/739624/23630367/c607323a-02b2-11e7-9f57-22bc6cf90a93.jpg)

![designbern_cute_robot](https://cloud.githubusercontent.com/assets/739624/23630371/c906876a-02b2-11e7-99bf-d4cf716d8c43.jpg)

/cc @huffeec @frabcus @awesomeliverpool

**Comment by huffeec** [comment]
I've just been to chat with the sewing club, they were thinking of something like this. (Sort of similar to the top images..)

![image](https://cloud.githubusercontent.com/assets/4748179/23631296/e4faaa66-02b5-11e7-9eee-72faa215510e.png)

I really like the idea of building in a screen on the back with instructions too, makes it more interactive.

**Comment by huffeec** [comment]
Talked with Dave about this at Maker day. He's looking at designs for the enclosure. 
Will post updates here but keep the ideas coming, or speak to Dave..

**Comment by drfraz** [comment]
Prototype foam body & perspex hard box for electronics made (see fomotest1.0 a & b in code section).
Initial consumer feedback seems positive for size & ease of throwing. Just need to cover it in fur....

**Comment by drfraz** [comment]
Rough sketches for Liv & Mo
![liv mo](https://cloud.githubusercontent.com/assets/19359833/24276553/743600c8-102f-11e7-95ab-86ca3de346ff.png)

**Comment by drfraz** [comment]
![img_20170408_151428782](https://cloud.githubusercontent.com/assets/19359833/24832616/3608232a-1cab-11e7-94ca-190c2ce84c59.jpg)

![img_20170408_115935844](https://cloud.githubusercontent.com/assets/19359833/24832618/412c2288-1cab-11e7-8009-a91affe0f6a3.jpg)

first fix

**Comment by drfraz** [comment]
If we can't get hold of the sewing club then this might help!
http://laurenvenell.com/epic-how-to-make-a-3-d-plush-pattern-from-a-2-d-drawing/

**Comment by drfraz** [comment]
![felting](https://cloud.githubusercontent.com/assets/19359833/25058966/5ddc2a10-2177-11e7-8af3-ffefb9690052.jpg)

**Comment by drfraz** [comment]
![2ndfix](https://cloud.githubusercontent.com/assets/19359833/25316905/c562aace-2866-11e7-8a89-407194b5d7c9.jpg)

Hope they are cute enough! Weight & feel seemed good with the camera in situ
