### ISSUE TITLE
Investigate phone wifi hotspot as source of Internet connection

### ISSUE THREAD

**Issue by zarino** [DoESLiverpool/fomo-camera#2]
If a mobile data board for the Raspberry Pi is proving expensive, could we instead assign each FOMOcam with a human "minder" who broadcasts a wifi hotspot for the FOMOcam to connect to?

Minders would need a phone, a sim card with sufficient data allowance and tethering enabled, and a spare USB battery pack, probably!!

**Comment by huffeec** [comment]
Yes, I think this is the way to go. All we'd really lose, (and maybe not even) would be the accurate location data, which isn't really a problem.

**Comment by drfraz** [comment]
Would a 3G modem dongle work OK? like one of these
 http://www.auto-gadget.com/index.php?route=product/product&product_id=58406&currency=GBP 
looks a lot cheaper than the specific raspberry pi modems & people seem to be using them OK.
Only downside seems to be the aesthetics but we could remove the cover!

**Comment by huffeec** [comment]
Have got and tested an o2 3g usb dongle. 
Works on Raspbian and ran for 9 hours on the battery and uploaded images fine. 
(I switched it off after nine hours to save data and because that's plenty long enough..)
