### ISSUE TITLE
Check Pyinstagram as a route to upload media to Instagram

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/fomo-camera#4]
Look into this as an option to access the Instagram API via Python

https://github.com/eseom/pyinstagram

**Comment by drfraz** [comment]
Here is a possible alternative
https://github.com/mgp25/Instagram-API

**Comment by huffeec** [comment]
I didn't have much confidence in the Instagram API for this, so I'm currently using ftp to transfer images to a webserver.
[fomocam.co.uk](http://fomocam.co.uk) is running a basic bootstrap page that displays the most recent image and has paginated thumbs for older images. I'll add some social media buttons to encourage sharing and make it easy for us to post highlights to instagram/twitter accounts.

**Comment by drfraz** [comment]
Yeah, if we are monitoring the site then we can ping off selected images every so often to the Instagram, twitter accounts, Police etc.

**Comment by huffeec** [comment]
This is working now, and no police were needed at Festevol
