### ISSUE TITLE
Name the cameras

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/fomo-camera#5]
Currently the cameras don't have particularly friendly names (fomocam1, fomocam2..)
Any suggestions for something a bit more engaging?

So far we've got FomoLiv and FomoMo....

**Comment by SayBeano** [comment]
Maybe FomoViv or just Vivian, after Vivian Maier for one?

Her photos were found a few years back [by someone](http://www.johnmaloof.com/) who bought the contents of a storage container, Vivian was traced from a self portrait and later a documentary was made. That's about the most fitting suggestion I have.

The story could be further incorporated into an RFID / NFC / QRC that people inheriting the cameras can scan and be taken off to wikipedia. Mayber.

**Comment by DoESsean** [comment]
FomoMoney and FomoProblems.

**Comment by drfraz** [comment]
![viv1](https://cloud.githubusercontent.com/assets/19359833/24276405/7ec0dbcc-102e-11e7-93a7-8e7fdcb5ac67.png)

Fomo Vivian (secret evil goth cam)
