### ISSUE TITLE
Bluecoats meeting

### ISSUE THREAD

**Issue by drfraz** [DoESLiverpool/fomo-camera#6]
Do you think we can meet with Bluecoats on Wednesday? 
We need to see where we can project images & find out what they expect from us!
It could be a good place to try & get the 2 cameras to meet up rather than set them off from. Possibly start 1 at the Library & 1 at the Cathedral

**Comment by huffeec** [comment]
Rob from Bluecoat is going to be around sometime today to talk about this. Do you want to chat with him? I've copied you into the email so you can pass on your phone number if you do.

**Comment by drfraz** [comment]
Hi Chris, I'm at DoES so free to talk, my number is 07887 901668 but I can
pop across to Bluecoats easily
Fraz

On 22 Mar 2017 10:48 am, "huffeec" <notifications@github.com> wrote:

Rob from Bluecoat is going to be around sometime today to talk about this.
Do you want to chat with him? I've copied you into the email so you can
pass on your phone number if you do.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/DoESLiverpool/fomo-camera/issues/6#issuecomment-288362075>,
or mute the thread

**Comment by huffeec** [comment]
Cool, Are you ok to chat with them?
Do you want me to pass on your number?

**Comment by huffeec** [comment]
Chasing my tail a bit this week. But will definitely have a time lapse
ready camera for tomorrow. and I'll get onto the sewing club now.
Hope the exams went well?

**Comment by drfraz** [comment]
Yes pass it on, just cutting the foam down to size. I will be down tomorrow
night so can catch up

**Comment by huffeec** [comment]
So in the mean time Rob has called me.

He's offering one of the two TV's in the foyer, connected to a laptop, and
a small table somewhere.
Does that sound ok?

They need to agree it with Marie-Anne though.

**Comment by drfraz** [comment]
That sounds great, I'll pop in in a bit and send a photo

**Comment by drfraz** [comment]
I guess it is one of these screens that they mentioned. It would certainly
get a lot of notice. We could use my old laptop as it doesn't matter if it
gets nicked.
Also friendly sized foam.

On 22 Mar 2017 11:30 am, "David Frazer" <lazy.morepork@gmail.com> wrote:

That sounds great, I'll pop in in a bit and send a photo
