### ISSUE TITLE
Testing times

### ISSUE THREAD

**Issue by drfraz** [DoESLiverpool/fomo-camera#7]
Good news that we can test Fomocam at the Invisible wind Factory on 30th April!

**Comment by drfraz** [comment]
I've opened this as a project. No idea if that's the right thing or not but I like the idea.

**Comment by huffeec** [comment]
Why not..

**Comment by drfraz** [comment]
![festevol17](https://cloud.githubusercontent.com/assets/19359833/25558765/5d5802a8-2d25-11e7-873d-2318f5279306.jpg)

**Comment by drfraz** [comment]
Pretty successful test run here are some of the main issues

Instructions aren't obvious : try parcel tags with them on.
              Web address on one side & instructions on the other?

Kids these days have short attention spans: try photo every 30 seconds.
               Should have enough data & means only 20 seconds when the camera isn't doing something.

IR camera produces some very weird colours: try to make it a feature.
              If we use it in Vivian & say that he sees the world in a different way which can be both disturbing   
               &/or beautiful. good for inclusivity of the differently able, autistic,etc & philosophical; is any           
               world view the right one? (Liberal arty types love this stuff!) 

 Very positive feedback & interest from most people with several wanting to buy one

**Comment by drfraz** [comment]
Also seems to be plenty of charge left after about 8 hours!

**Comment by huffeec** [comment]
I also learned I'm going to need a backup battery for my own phone..
