### ISSUE TITLE
Create instructions label

### ISSUE THREAD

**Issue by huffeec** [DoESLiverpool/fomo-camera#9]
Make a label for the cameras that makes the instructions more obvious.
Include text from back of camera and web address.

Needs to be fairly durable so more than card. What fabrics etch well? Leather?

**Comment by drfraz** [comment]
Might be best to do thick card then laminate it once printed. Do we have access to a laminater?
Otherwise I could have a look around Abakhan tomorrow morning.

**Comment by drfraz** [comment]
thin plywood could work & I could stick some Danish oil on, for that retro look

**Comment by drfraz** [comment]
Files uploaded & wooden tags made for each camera
